services:
  - type: web
    name: rms-dash
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --workers=2 --threads=4 --timeout=120
    healthCheckPath: /
    envVars:
      - key: RMS_SECRET
        generateValue: true
      - key: RMS_DB_PATH
        value: /opt/render/project/src/storage/rms.db
      - key: RMS_UPLOAD_DIR
        value: /opt/render/project/src/storage/uploads
    disk:
      name: data
      mountPath: /opt/render/project/src/storage
      sizeGB: 1
